# Generated by Django 4.2.1 on 2023-09-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cont_d',
            field=models.CharField(default='Nothing', max_length=20000),
        ),
        migrations.AddField(
            model_name='blog',
            name='recommend',
            field=models.CharField(default='Nothing', max_length=200),
        ),
    ]
