# Generated by Django 4.2.1 on 2023-09-22 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_blog_students_delete_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='file_path_html',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='recommended_on_google',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
