# Generated by Django 4.2 on 2023-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('posted_date', models.DateField()),
                ('posted_time', models.TimeField()),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('total_comments', models.IntegerField()),
                ('recommended_on_google', models.IntegerField()),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
